name: function_widget
description: A Flutter package that provides a macro to generate StatelessWidget from a function, reducing boilerplate code.
version: 0.0.1-dev.1
homepage: https://github.com/p4-k4/flutter_package_function_widget
repository: https://github.com/p4-k4/flutter_package_function_widget

environment:
  sdk: ^3.6.0-0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.3-main.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - widgets
  - macros
  - code-generation
  - flutter

flutter:
